"""Headless Godot playtest: run a generated prototype and measure it.

This is the missing half of the pipeline. Everything before this point proves
the prototype *compiles*; this proves the loop is *reachable*: a scripted bot
loads the real main scene, drives the real input actions, and reports what the
generated ``game_manager`` actually decided.

Two rules shape this module, both learned by running the engine:

1. **The probe runs outside the project.** Godot takes ``--script <absolute
   path>`` with ``--path <project>``, so nothing has to be written into the
   generated project and the playtest leaves the artefact untouched.

2. **Duration comes from the engine, never from frames.** A headless run
   advances ``_process`` far faster than real time (measured: 439 frames for
   3.0 seconds of game time), so a frame count is not a duration and a frame
   time is not a performance number. ``session_seconds`` is read back from
   ``game_manager._elapsed``.

What this can and cannot say: it is a **lower bound on playability**. A bot
can prove the objective is reachable, that failure fires, and that the run
restarts. It cannot say the slice is fun, and the report says so out loud.
"""

from __future__ import annotations

import json
import math
import subprocess
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path

from fantasy_agent.contracts import (
    PlaytestAggregate,
    PlaytestFinding,
    PlaytestReport,
    PlaytestRequest,
    PlaytestSample,
)
from fantasy_agent.local_tools import _find_godot
from fantasy_agent.path_safety import WorkspacePathError, is_absolute_path, resolve_workspace_path
from fantasy_agent.pipeline_state import resume_stage_for
from fantasy_agent.process_runner import run_streaming

PROBE_FILENAME = "playtest_probe.gd"
PLAYTEST_DIRNAME = Path("generated") / "playtest"
RESULT_PREFIX = "PLAYTEST-RESULT "

#: A run where the player never moved this far is not a playable run.
MIN_PLAYER_MOVE_METERS = 1.0
#: Below this a session ended before the loop could be felt. Warning only:
#: a bot is a poor player, so a short run is evidence, not proof.
SHORT_SESSION_SECONDS = 5.0
_SCRIPT_ERROR_MARKERS = ("SCRIPT ERROR", "Parse Error")
_MAX_REPORTED_SCRIPT_ERRORS = 10

_PROBE_TEMPLATE = '''extends SceneTree

# Generated by Fantasy Agent -- do not edit.
# Runs the prototype headlessly and reports what actually happened inside the
# engine. Everything here is a LOWER BOUND on playability: a scripted bot can
# prove the loop is reachable, it cannot prove the slice is fun.

const RESULT_PREFIX := "PLAYTEST-RESULT "
const MAX_RUNS := __RUNS__
const MAX_FRAMES := __MAX_FRAMES__
const INPUT_PLAN := "__INPUT_PLAN__"
const MIN_MOVE := __MIN_MOVE__
const OUT_FILE := "__OUT_FILE__"

var _root: Window = null
var _frames := 0
var _start_msec := 0
var _runs: Array = []
var _attempts := 0
var _recorded_id := 0
var _manager: Node = null
var _has_player := false
var _player_last := Vector3.ZERO
var _moved := 0.0
var _run_start_msec := 0
var _saw_player := false
var _saw_manager := false
var _scene_path := ""
var _actions: Array = []
var _error := ""
var _degraded_reason := ""


func _initialize() -> void:
	_start_msec = Time.get_ticks_msec()
	_run_start_msec = _start_msec
	_root = root
	var cfg := ConfigFile.new()
	if cfg.load("res://project.godot") != OK:
		_error = "project.godot could not be read"
		_finish()
		return
	_scene_path = str(cfg.get_value("application", "run/main_scene", ""))
	_actions = cfg.get_section_keys("input")
	if _scene_path == "":
		_error = "run/main_scene is not set in project.godot"
		_finish()
		return
	if change_scene_to_file(_scene_path) != OK:
		_error = "the main scene could not be loaded: " + _scene_path
		_finish()
		return
	if INPUT_PLAN != "idle" and _actions.has("move_forward"):
		Input.action_press("move_forward")


func _process(_delta: float) -> bool:
	_frames += 1
	var tree := _root.get_tree()
	var player := tree.get_first_node_in_group("player")
	if player != null and player is Node3D:
		_saw_player = true
		if not _has_player:
			_has_player = true
			_player_last = player.global_position
		else:
			_moved += _player_last.distance_to(player.global_position)
			_player_last = player.global_position
	var manager := tree.get_first_node_in_group("game_manager")
	if manager != null:
		_saw_manager = true
		if manager != _manager:
			_manager = manager
			_recorded_id = 0
		if bool(manager.get("_ended")) and _recorded_id != manager.get_instance_id():
			_record(manager)
	if INPUT_PLAN == "forward_and_jump" and _actions.has("jump"):
		if _frames % 90 == 0:
			Input.action_press("jump")
		elif _frames % 90 == 6:
			Input.action_release("jump")
	if _attempts >= MAX_RUNS or _frames >= MAX_FRAMES:
		_finish()
		return true
	return false


func _record(manager: Node) -> void:
	_recorded_id = manager.get_instance_id()
	_attempts += 1
	# A project generated before the structured outcome existed answers null
	# here; "ended" keeps the run countable instead of silently vanishing.
	var raw_outcome = manager.get("last_outcome")
	var raw_reason = manager.get("last_reason")
	var raw_progress = manager.get("_progress")
	var outcome := "ended" if raw_outcome == null else str(raw_outcome)
	var reason := "" if raw_reason == null else str(raw_reason)
	var progress := 0 if raw_progress == null else int(raw_progress)
	_runs.append({
		"run_index": _attempts - 1,
		"outcome": outcome,
		"reason": reason,
		"session_seconds": float(manager.get("_elapsed")),
		"progress": progress,
		"player_moved_distance": _moved,
		"frames": _frames,
		"wall_msec": Time.get_ticks_msec() - _run_start_msec,
		"playable": _saw_player and _moved > MIN_MOVE,
	})
	# The next run reloads the scene, so the player teleports back to spawn.
	# Dropping the tracked point makes that jump nobody's distance, and
	# rebasing the clock keeps wall_msec about *this* run, not the whole
	# playtest (the payload still reports the total).
	_moved = 0.0
	_has_player = false
	_run_start_msec = Time.get_ticks_msec()


func _finish() -> void:
	if not _saw_player:
		_degraded_reason = "no node in the player group: the project was generated without gameplay scripts"
	elif not _saw_manager:
		_degraded_reason = "no node in the game_manager group: win and fail cannot be observed"
	if _error == "" and _attempts < MAX_RUNS:
		_runs.append({
			"run_index": _attempts,
			"outcome": "timeout",
			"reason": "no win and no failure before the frame budget ran out",
			"session_seconds": 0.0,
			"progress": 0,
			"player_moved_distance": _moved,
			"frames": _frames,
			"wall_msec": Time.get_ticks_msec() - _run_start_msec,
			"playable": false,
		})
	var payload := {
		"scene_path": _scene_path,
		"actions": _actions,
		"saw_player": _saw_player,
		"saw_manager": _saw_manager,
		"degraded_reason": _degraded_reason,
		"error": _error,
		"frames": _frames,
		"wall_msec": Time.get_ticks_msec() - _start_msec,
		"runs": _runs,
	}
	var text := JSON.stringify(payload)
	print(RESULT_PREFIX + text)
	var handle := FileAccess.open(OUT_FILE, FileAccess.WRITE)
	if handle != null:
		handle.store_string(text)
		handle.close()
	quit(0 if _error == "" else 3)
'''


def render_probe_script(
    *,
    runs: int,
    max_frames: int,
    input_plan: str,
    out_file: str,
) -> str:
    """Render the GDScript probe with its budget baked in."""

    return (
        _PROBE_TEMPLATE.replace("__RUNS__", str(runs))
        .replace("__MAX_FRAMES__", str(max_frames))
        .replace("__INPUT_PLAN__", input_plan)
        .replace("__OUT_FILE__", out_file)
        .replace("__MIN_MOVE__", str(MIN_PLAYER_MOVE_METERS))
    )


def _session_dir_name(session_id: str) -> str:
    """Reject a session id that is anything but one plain path segment."""

    if not session_id:
        raise WorkspacePathError("session_id must not be empty")
    if is_absolute_path(session_id) or session_id in {".", ".."}:
        raise WorkspacePathError(f"session_id must be one path segment, not a path: {session_id}")
    if "/" in session_id or "\\" in session_id:
        raise WorkspacePathError(f"session_id must not contain a path separator: {session_id}")
    return session_id


def playtest_artifact_paths(workspace_root: Path | str, session_id: str) -> dict[str, Path]:
    """Every file one playtest writes, scoped to one session directory.

    ``session_id`` reaches here from the Studio request body, so it goes
    through the same workspace guard every other caller-supplied path in this
    repo uses. An unchecked id would otherwise walk the session directory out
    of the repo (``..``) or land anywhere on disk (``C:/...``), which is worse
    than a noisy error because the report would still look valid.
    """

    base = resolve_workspace_path(
        f"{PLAYTEST_DIRNAME.as_posix()}/{_session_dir_name(session_id)}",
        workspace_root=workspace_root,
        required_prefix=PLAYTEST_DIRNAME.as_posix(),
    )
    return {
        "dir": base,
        "probe": base / PROBE_FILENAME,
        "payload": base / "playtest-payload.json",
        "stdout": base / "godot-stdout.log",
        "stderr": base / "godot-stderr.log",
        "report": base / "playtest-report.json",
    }


def planned_playtest_side_effects(request: PlaytestRequest) -> list[str]:
    """What confirming a playtest actually does, for the two-step gate."""

    return [
        "Write a headless probe script under generated/playtest/ (outside the project)",
        "Launch Godot headless against the generated project and drive it with scripted input",
        (
            f"Play up to {request.runs} attempts inside one engine process, capped at "
            f"{request.max_wall_seconds:.0f}s wall clock"
        ),
        "Write the measured playtest report under generated/playtest/",
    ]


def _percentile(values: list[float], fraction: float) -> float:
    if not values:
        return 0.0
    ordered = sorted(values)
    if len(ordered) == 1:
        return ordered[0]
    rank = (len(ordered) - 1) * fraction
    low = math.floor(rank)
    high = math.ceil(rank)
    if low == high:
        return float(ordered[int(rank)])
    return float(ordered[low] * (high - rank) + ordered[high] * (rank - low))


def _collect_script_errors(stderr_text: str) -> list[str]:
    seen: list[str] = []
    for line in stderr_text.splitlines():
        if any(marker in line for marker in _SCRIPT_ERROR_MARKERS):
            cleaned = line.strip()
            if cleaned and cleaned not in seen:
                seen.append(cleaned)
    return seen[:_MAX_REPORTED_SCRIPT_ERRORS]


def _sample_from_payload(entry: dict, *, degraded_reason: str, script_errors: list[str]) -> PlaytestSample:
    outcome = str(entry.get("outcome", ""))
    reason = str(entry.get("reason", ""))
    failure_reasons: dict[str, int] = {}
    if outcome == "fail" and reason:
        failure_reasons[reason] = 1
    moved = float(entry.get("player_moved_distance", 0.0) or 0.0)
    return PlaytestSample(
        run_index=int(entry.get("run_index", 0) or 0),
        outcome=outcome,
        reason=reason,
        session_seconds=float(entry.get("session_seconds", 0.0) or 0.0),
        attempts=1,
        wins=1 if outcome == "win" else 0,
        failures=1 if outcome == "fail" else 0,
        player_moved_distance=moved,
        progress=int(entry.get("progress", 0) or 0),
        frames=int(entry.get("frames", 0) or 0),
        wall_msec=int(entry.get("wall_msec", 0) or 0),
        playable=bool(entry.get("playable", False)),
        degraded=bool(degraded_reason),
        degraded_reason=degraded_reason,
        failure_reasons=failure_reasons,
        script_errors=list(script_errors),
    )


def aggregate_samples(samples: list[PlaytestSample]) -> PlaytestAggregate:
    """Aggregate by ``outcome``, not by the per-run counters.

    A sample can carry ``outcome="fail"`` with ``failures=0`` (a payload built
    by hand, or a project generated before the counters existed), and counting
    the counters then reports an empty verdict for a run that plainly ended.
    """

    sessions = [s.session_seconds for s in samples]
    wins = sum(1 for s in samples if s.outcome == "win")
    failures = sum(1 for s in samples if s.outcome == "fail")
    timeouts = sum(1 for s in samples if s.outcome == "timeout")
    playable_runs = sum(1 for s in samples if s.playable)
    reasons: dict[str, int] = {}
    errors: list[str] = []
    for sample in samples:
        for reason, count in sample.failure_reasons.items():
            reasons[reason] = reasons.get(reason, 0) + count
        for err in sample.script_errors:
            if err not in errors:
                errors.append(err)
    total = len(samples)
    return PlaytestAggregate(
        runs=total,
        playable_runs=playable_runs,
        degraded_runs=sum(1 for s in samples if s.degraded),
        wins=wins,
        failures=failures,
        timeouts=timeouts,
        win_rate=(wins / total) if total else 0.0,
        playable_rate=(playable_runs / total) if total else 0.0,
        session_seconds_p50=_percentile(sessions, 0.5),
        session_seconds_p95=_percentile(sessions, 0.95),
        failure_reasons=reasons,
        script_errors=errors[:_MAX_REPORTED_SCRIPT_ERRORS],
    )


def _finding(
    code: str,
    severity: str,
    message: str,
    rework_target: str,
) -> PlaytestFinding:
    return PlaytestFinding(
        code=code,
        severity=severity,  # type: ignore[arg-type]
        message=message,
        rework_target=rework_target,  # type: ignore[arg-type]
        resume_stage=resume_stage_for(rework_target) or "",
    )


def build_findings(
    samples: list[PlaytestSample],
    aggregate: PlaytestAggregate,
) -> list[PlaytestFinding]:
    """Translate measurements into rework targets.

    Every finding names the same ``rework_target`` vocabulary as ``preflight``
    so the console reuses one "resume from here" control.

    The session-length target is deliberately *not* an input here. A bot
    cannot stand in for a player deciding to keep playing, so a short run is
    reported as an observation (``session_too_short``) and the target itself
    is only ever discussed in ``_goal_notes``.
    """

    findings: list[PlaytestFinding] = []
    if aggregate.script_errors:
        findings.append(
            _finding(
                "script_error",
                "blocking",
                f"Godot reported {len(aggregate.script_errors)} script error(s) while the prototype was running",
                "godot_plan",
            )
        )
    if aggregate.runs and aggregate.degraded_runs == aggregate.runs:
        reasons = {s.degraded_reason for s in samples if s.degraded_reason}
        detail = "; ".join(sorted(reasons)) or "the probe could not observe the loop"
        findings.append(
            _finding(
                "not_playable",
                "blocking",
                f"No run was playable: {detail}",
                "godot_plan",
            )
        )
    stuck = [s for s in samples if not s.degraded and s.player_moved_distance < MIN_PLAYER_MOVE_METERS]
    if stuck and len(stuck) == len([s for s in samples if not s.degraded]):
        findings.append(
            _finding(
                "player_stuck",
                "blocking",
                f"The player never moved more than {MIN_PLAYER_MOVE_METERS} m in any run",
                "godot_plan",
            )
        )
    if aggregate.runs and aggregate.timeouts == aggregate.runs:
        findings.append(
            _finding(
                "never_ended",
                "warning",
                "No run reached a win or a failure inside the frame budget",
                "spec",
            )
        )
    elif aggregate.runs and aggregate.failures and aggregate.wins == 0:
        findings.append(
            _finding(
                "no_win_path",
                "warning",
                "Every run ended in failure: the win path was never reached by the bot",
                "spec",
            )
        )
    if (
        aggregate.session_seconds_p50 > 0.0
        and aggregate.session_seconds_p50 < SHORT_SESSION_SECONDS
    ):
        findings.append(
            _finding(
                "session_too_short",
                "warning",
                f"Median run lasted {aggregate.session_seconds_p50:.1f}s, under the {SHORT_SESSION_SECONDS:.0f}s floor",
                "spec",
            )
        )
    return findings


def _goal_notes(request: PlaytestRequest) -> list[str]:
    notes = [
        (
            "A scripted bot proves the loop is reachable, not that the slice is fun; "
            "treat this report as a lower bound on playability."
        ),
        (
            "Durations are engine-internal seconds read from game_manager, never frame counts: "
            "a headless run advances frames faster than real time."
        ),
    ]
    if request.goal_session_minutes:
        notes.append(
            f"The {request.goal_session_minutes:g}-minute session target is not judged by this "
            "playtest: a bot cannot stand in for a player deciding to keep playing."
        )
    return notes


def run_playtest(
    request: PlaytestRequest,
    *,
    workspace_root: Path | str,
    session_id: str | None = None,
) -> PlaytestReport:
    """Run the headless playtest and return the measured report."""

    stamp = session_id or datetime.now(UTC).strftime("%Y%m%d_%H%M%S")
    paths = playtest_artifact_paths(workspace_root, stamp)
    executable = request.godot_executable or _find_godot() or ""
    project_dir = Path(request.project_dir)

    report = PlaytestReport(
        project_dir=str(project_dir),
        engine_executable=executable,
        runs_requested=request.runs,
        goal_session_minutes=request.goal_session_minutes,
        generated_at=datetime.now(UTC).isoformat(timespec="seconds"),
        goal_notes=_goal_notes(request),
        artifact_paths=[p.as_posix() for p in (paths["probe"], paths["report"])],
    )

    if not executable:
        report.findings = [
            _finding(
                "engine_missing",
                "blocking",
                "No Godot executable was found; set GODOT_EXECUTABLE or install Godot 4",
                "flags",
            )
        ]
        report.status = "failed"
        return report
    if not (project_dir / "project.godot").is_file():
        report.findings = [
            _finding(
                "project_missing",
                "blocking",
                f"{project_dir.as_posix()} has no project.godot: generate the prototype first",
                "godot_plan",
            )
        ]
        report.status = "failed"
        return report

    # Only now does anything touch the disk: an engine we cannot launch writes
    # no probe, no report and no session directory.
    paths["dir"].mkdir(parents=True, exist_ok=True)
    paths["probe"].write_text(
        render_probe_script(
            runs=request.runs,
            max_frames=request.max_frames,
            input_plan=request.input_plan,
            out_file=paths["payload"].as_posix(),
        ),
        encoding="utf-8",
    )

    command = [
        executable,
        "--headless",
        "--path",
        str(project_dir),
        "--script",
        str(paths["probe"]),
    ]
    timeout = request.max_wall_seconds
    stderr_text = ""
    try:
        completed = run_streaming(
            command,
            stdout_path=paths["stdout"],
            stderr_path=paths["stderr"],
            timeout=timeout,
        )
        stdout_text = completed.stdout or ""
        stderr_text = completed.stderr or ""
    except subprocess.TimeoutExpired:
        stdout_text = _read_log(paths["stdout"])
        stderr_text = _read_log(paths["stderr"])
        report.findings.append(
            _finding(
                "playtest_timeout",
                "warning",
                f"The playtest exceeded its {timeout:.0f}s wall clock budget and was stopped",
                "flags",
            )
        )

    payload = _parse_payload(stdout_text, paths["payload"])
    script_errors = _collect_script_errors(stderr_text)
    degraded_reason = str(payload.get("degraded_reason", "") or "")
    if str(payload.get("error", "") or ""):
        script_errors = [str(payload["error"]), *script_errors]

    samples = [
        _sample_from_payload(entry, degraded_reason=degraded_reason, script_errors=script_errors)
        for entry in payload.get("runs", [])
        if isinstance(entry, dict)
    ]
    report.samples = samples
    report.aggregate = aggregate_samples(samples)
    report.findings.extend(
        build_findings(samples, report.aggregate)
    )
    report.status = _status_for(report.findings, report.aggregate)

    paths["report"].write_text(
        json.dumps(report.model_dump(), ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    return report


def _read_log(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""


def _parse_payload(stdout_text: str, payload_path: Path) -> dict:
    for line in stdout_text.splitlines():
        if RESULT_PREFIX in line:
            _, _, raw = line.partition(RESULT_PREFIX)
            try:
                loaded = json.loads(raw.strip())
            except ValueError:
                continue
            if isinstance(loaded, dict):
                return loaded
    try:
        loaded = json.loads(payload_path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}
    return loaded if isinstance(loaded, dict) else {}


def _status_for(findings: list[PlaytestFinding], aggregate: PlaytestAggregate) -> str:
    if any(f.severity == "blocking" for f in findings):
        return "failed"
    if findings or aggregate.runs == 0:
        return "warning"
    return "passed"


@dataclass
class PlaytestResult:
    """Playtest outcome shaped for the Studio job registry.

    Mirrors ``executor.ExecutionResult``: ``confirmed=False`` produces a
    ``confirmation_required`` payload that only lists side effects, so the
    two-step gate never launches an engine.
    """

    #: Job vocabulary, the same one ``executor.ExecutionResult`` speaks:
    #: ``confirmation_required | done | failed``. The verdict about the
    #: prototype is not here -- it is ``report.status``. Collapsing the two
    #: would make a run that *measured* a failure look like a run that broke.
    status: str
    project_dir: str = ""
    report: PlaytestReport | None = None
    planned_side_effects: list[str] = field(default_factory=list)
    summary: str = ""

    @property
    def ok(self) -> bool:
        return self.status == "done"


def summarize_playtest(report: PlaytestReport) -> str:
    """One CLI/console-friendly paragraph."""

    agg = report.aggregate
    lines = [
        f"[{report.status}] playtest {report.project_dir}",
        f"  runs: {agg.runs} requested {report.runs_requested}, playable {agg.playable_runs}, degraded {agg.degraded_runs}",
        f"  outcomes: win {agg.wins}, fail {agg.failures}, timeout {agg.timeouts}",
        f"  session seconds: p50 {agg.session_seconds_p50:.1f}, p95 {agg.session_seconds_p95:.1f}",
    ]
    for finding in report.findings:
        lines.append(f"  - [{finding.severity}] {finding.code}: {finding.message}")
        lines.append(f"      rework: {finding.rework_target} (resume: {finding.resume_stage or 'n/a'})")
    for note in report.goal_notes:
        lines.append(f"  note: {note}")
    return "\n".join(lines)
