from __future__ import annotations

from fantasy_agent.contracts import MCPToolContract


def initial_mcp_contracts() -> list[MCPToolContract]:
    return [
        MCPToolContract(
            name="create_project_structure",
            server="unreal-mcp",
            input_schema_ref="mcp/unreal-mcp/tools.yaml#create_project_structure",
            output_schema_ref="mcp/unreal-mcp/tools.yaml#create_project_structure.output",
            side_effects=[
                "optionally writes generated .uproject, Config, setup script, and content manifest",
                "optionally creates generated Unreal content folders",
            ],
            safety_checks=[
                "project path must be generated/unreal",
                "content folders must start with Content/",
                "engine version must be explicit",
            ],
        ),
        MCPToolContract(
            name="run_editor_commandlet",
            server="unreal-mcp",
            input_schema_ref="mcp/unreal-mcp/tools.yaml#run_editor_commandlet",
            output_schema_ref="mcp/unreal-mcp/tools.yaml#run_editor_commandlet.output",
            side_effects=["launches Unreal Editor data validation"],
            safety_checks=[
                "requires confirmed execution",
                "project file must be generated/unreal/*.uproject",
                "commandlet allowlist is limited to UE DataValidation",
                "timeout required",
                "logs captured under generated/logs/unreal",
            ],
        ),
        MCPToolContract(
            name="prepare_asset_ingest",
            server="unreal-mcp",
            input_schema_ref="mcp/unreal-mcp/tools.yaml#prepare_asset_ingest",
            output_schema_ref="mcp/unreal-mcp/tools.yaml#prepare_asset_ingest.output",
            side_effects=[
                "optionally writes Unreal Python import script",
                "optionally writes asset ingest manifest",
            ],
            safety_checks=[
                "project file must be generated/unreal/*.uproject",
                "Blender assets must be generated/assets",
                "ComfyUI images must be generated/comfyui",
                "ComfyUI imports remain review references",
            ],
        ),
        MCPToolContract(
            name="run_asset_ingest",
            server="unreal-mcp",
            input_schema_ref="mcp/unreal-mcp/tools.yaml#run_asset_ingest",
            output_schema_ref="mcp/unreal-mcp/tools.yaml#run_asset_ingest.output",
            side_effects=["launches Unreal Editor", "imports assets into project content"],
            safety_checks=[
                "requires confirmed execution",
                "project file must be generated/unreal/*.uproject",
                "script must be generated/unreal/*.py",
                "logs captured under generated/logs/unreal",
            ],
        ),
        MCPToolContract(
            name="validate_asset_ingest",
            server="unreal-mcp",
            input_schema_ref="mcp/unreal-mcp/tools.yaml#validate_asset_ingest",
            output_schema_ref="mcp/unreal-mcp/tools.yaml#validate_asset_ingest.output",
            side_effects=["reads generated Unreal asset ingest manifest and source file paths"],
            safety_checks=[
                "does not launch Unreal",
                "ingest manifest must be generated/unreal",
                "asset names and UCX collision names must be Unreal-safe",
                "source files must stay under generated/assets or generated/comfyui",
            ],
        ),
        MCPToolContract(
            name="prepare_level_assembly",
            server="unreal-mcp",
            input_schema_ref="mcp/unreal-mcp/tools.yaml#prepare_level_assembly",
            output_schema_ref="mcp/unreal-mcp/tools.yaml#prepare_level_assembly.output",
            side_effects=[
                "optionally writes Unreal Python level assembly script",
                "optionally writes level assembly manifest",
            ],
            safety_checks=[
                "project file must be generated/unreal/*.uproject",
                "source ingest manifest must be generated/unreal",
                "map path must stay under /Game/Maps",
            ],
        ),
        MCPToolContract(
            name="validate_level_assembly",
            server="unreal-mcp",
            input_schema_ref="mcp/unreal-mcp/tools.yaml#validate_level_assembly",
            output_schema_ref="mcp/unreal-mcp/tools.yaml#validate_level_assembly.output",
            side_effects=["reads generated Unreal level assembly manifest and asset paths"],
            safety_checks=[
                "does not launch Unreal",
                "level manifest must be generated/unreal",
                "route must include floor, objective, and exit roles",
                "imported asset paths must resolve to generated project Content files",
            ],
        ),
        MCPToolContract(
            name="run_level_assembly",
            server="unreal-mcp",
            input_schema_ref="mcp/unreal-mcp/tools.yaml#run_level_assembly",
            output_schema_ref="mcp/unreal-mcp/tools.yaml#run_level_assembly.output",
            side_effects=["launches Unreal Editor", "writes or updates generated map assets"],
            safety_checks=[
                "requires confirmed execution",
                "project file must be generated/unreal/*.uproject",
                "assembly script must be generated/unreal/*.py",
                "logs captured under generated/logs/unreal",
            ],
        ),
        MCPToolContract(
            name="generate_blender_script",
            server="blender-mcp",
            input_schema_ref="mcp/blender-mcp/tools.yaml#generate_blender_script",
            output_schema_ref="mcp/blender-mcp/tools.yaml#generate_blender_script.output",
            side_effects=["optionally writes generated Blender scripts and import manifests"],
            safety_checks=[
                "script path must be generated/blender",
                "manifest path must be generated",
                "export paths must be generated/assets",
            ],
        ),
        MCPToolContract(
            name="generate_asset_batch",
            server="blender-mcp",
            input_schema_ref="mcp/blender-mcp/tools.yaml#generate_asset_batch",
            output_schema_ref="mcp/blender-mcp/tools.yaml#generate_asset_batch.output",
            side_effects=["runs Blender Python", "writes mesh exports"],
            safety_checks=[
                "requires confirmed execution",
                "export path must be generated/assets",
                "script must avoid external downloads",
                "logs captured under generated/logs/blender",
            ],
        ),
        MCPToolContract(
            name="create_godot_project_structure",
            server="godot-mcp",
            input_schema_ref="mcp/godot-mcp/tools.yaml#create_godot_project_structure",
            output_schema_ref="mcp/godot-mcp/tools.yaml#create_godot_project_structure.output",
            side_effects=[
                "optionally writes generated Godot project.godot, scenes, scripts, and manifest",
                "optionally creates generated Godot asset and reference folders",
            ],
            safety_checks=[
                "project path must be generated/godot",
                "scene paths must stay under generated/godot and end with .tscn",
                "script paths must stay under generated/godot and end with .gd",
            ],
        ),
        MCPToolContract(
            name="validate_godot_project",
            server="godot-mcp",
            input_schema_ref="mcp/godot-mcp/tools.yaml#validate_godot_project",
            output_schema_ref="mcp/godot-mcp/tools.yaml#validate_godot_project.output",
            side_effects=["reads generated Godot project files"],
            safety_checks=[
                "does not launch Godot",
                "project file must be generated/godot/*/project.godot",
                "main scene and scripts are checked before import",
            ],
        ),
        MCPToolContract(
            name="run_godot_import",
            server="godot-mcp",
            input_schema_ref="mcp/godot-mcp/tools.yaml#run_godot_import",
            output_schema_ref="mcp/godot-mcp/tools.yaml#run_godot_import.output",
            side_effects=["launches Godot headless import", "writes .godot import metadata"],
            safety_checks=[
                "requires confirmed execution",
                "project file must be generated/godot/*/project.godot",
                "logs captured under generated/logs/godot",
            ],
        ),
        MCPToolContract(
            name="probe_comfyui_capabilities",
            server="comfyui-mcp",
            input_schema_ref="mcp/comfyui-mcp/tools.yaml#probe_comfyui_capabilities",
            output_schema_ref="mcp/comfyui-mcp/tools.yaml#probe_comfyui_capabilities.output",
            side_effects=["reads local ComfyUI HTTP capability endpoints"],
            safety_checks=[
                "does not submit prompts",
                "remote endpoints require explicit approval",
                "reports missing checkpoint models before execution",
            ],
        ),
        MCPToolContract(
            name="prepare_visual_reference_workflows",
            server="comfyui-mcp",
            input_schema_ref="mcp/comfyui-mcp/tools.yaml#prepare_visual_reference_workflows",
            output_schema_ref="mcp/comfyui-mcp/tools.yaml#prepare_visual_reference_workflows.output",
            side_effects=["optionally writes prepared ComfyUI workflow JSON and run manifests"],
            safety_checks=[
                "workflow templates must be templates/comfyui",
                "output path must be generated/comfyui",
                "jobs must reference gameplay constraints",
            ],
        ),
        MCPToolContract(
            name="run_visual_reference_workflow",
            server="comfyui-mcp",
            input_schema_ref="mcp/comfyui-mcp/tools.yaml#run_visual_reference_workflow",
            output_schema_ref="mcp/comfyui-mcp/tools.yaml#run_visual_reference_workflow.output",
            side_effects=["submits ComfyUI prompt jobs", "writes generated reference images"],
            safety_checks=[
                "requires confirmed execution",
                "ComfyUI endpoint must be local or explicitly approved",
                "output path must be generated/comfyui",
                "jobs must reference gameplay constraints",
                "workflow templates must be templates/comfyui",
                "required nodes and checkpoints must pass preflight before queueing",
            ],
        ),
        MCPToolContract(
            name="publish_prototype_branch",
            server="github-mcp",
            input_schema_ref="mcp/github-mcp/tools.yaml#publish_prototype_branch",
            output_schema_ref="mcp/github-mcp/tools.yaml#publish_prototype_branch.output",
            side_effects=["creates branch", "opens pull request"],
            safety_checks=["requires clean generated manifest", "never commits secrets"],
        ),
    ]
