from __future__ import annotations

from fantasy_agent.contracts import (
    BlenderAssetJob,
    BlenderAssetPlan,
    BlenderAssetKind,
    ComfyUIPromptJob,
    ComfyUIVisualPlan,
    DirectorBuildPlan,
    DirectorTaskBreakdown,
    GameplaySpec,
    PromptRequest,
    ProductionTask,
    QAPlan,
    UnrealProjectPlan,
)
from fantasy_agent.blender_codegen import enrich_blender_plan, slugify
from fantasy_agent.gdd import render_gdd
from fantasy_agent.generation import design_from_prompt


BLENDER_KIT_JOBS: tuple[tuple[str, str, BlenderAssetKind], ...] = (
    (
        "modular_wall_400",
        "Reusable modular wall for blocking sightlines and routes.",
        "modular_wall",
    ),
    ("interaction_door", "Readable door or gate for lock, key, or route-change tests.", "door"),
    ("traversal_ramp", "Simple ramp for vertical movement and route readability tests.", "ramp"),
    (
        "hazard_marker",
        "Readable hazard marker for pressure, danger, or failure feedback.",
        "hazard_marker",
    ),
    (
        "objective_prop",
        "Readable objective prop for interaction and pickup testing.",
        "objective_prop",
    ),
    ("exit_gate", "Readable exit gate for win-state and extraction tests.", "exit_gate"),
    (
        "ui_proxy_mesh",
        "World-space UI proxy mesh for objective and pressure readability.",
        "ui_proxy_mesh",
    ),
)

DIRECTOR_NEXT_ACTIONS = [
    "Review generated gameplay spec for loop coherence",
    "Export gameplay spec and GDD into generated/",
    "Run Blender greybox asset job",
    "Run ComfyUI reference jobs only after gameplay readability needs are approved",
    "Create UE project structure and import generated assets",
    "Run QA smoke test before adding visual polish",
]


def prepare_unreal_project(spec: GameplaySpec, engine_version: str = "UE5") -> UnrealProjectPlan:
    project_slug = "".join(part for part in spec.title.title().split()) or "FantasyPrototype"
    return UnrealProjectPlan(
        project_name=project_slug,
        engine_version=engine_version,
        template="third-person",
        plugins=["EnhancedInput", "GameplayTags", "Niagara"],
        folders=[
            "Content/Blueprints/CoreLoop",
            "Content/Blueprints/Interactables",
            "Content/Maps",
            "Content/UI",
            "Content/Art/Generated",
            "Content/Data",
        ],
        gameplay_classes=[
            "BP_PlayerPrototypePawn",
            "BP_ObjectiveStateComponent",
            "BP_PressureClockComponent",
            "BP_InteractableBase",
            "BP_RunResultSubsystem",
        ],
        blueprints=[
            "BP_ObjectiveDirector",
            "BP_LevelBeatTrigger",
            "BP_HazardPressureSource",
            "WBP_ObjectiveTracker",
            "WBP_RunSummary",
        ],
        maps=["M_Prototype_Greybox", "M_Prototype_TestGym"],
        automation_steps=[
            "Create UE project from template",
            "Enable required plugins",
            "Create content folders",
            "Import generated greybox assets",
            "Create data assets from gameplay DSL",
            "Run map validation commandlet",
        ],
        handoff_artifacts=[
            "generated/gameplay-spec.yaml",
            "generated/gdd.md",
            "generated/unreal-project-plan.yaml",
        ],
    )


def prepare_blender_assets(spec: GameplaySpec) -> BlenderAssetPlan:
    jobs: list[BlenderAssetJob] = []
    seen_kinds: set[BlenderAssetKind] = set()
    for asset in spec.asset_needs:
        asset_name = slugify(asset)
        jobs.append(
            BlenderAssetJob(
                asset_name=asset_name,
                purpose=asset,
                primitive_strategy=(
                    "modular low-poly mesh with bevels only where readability improves play"
                ),
                export_path=f"generated/assets/{asset_name}.fbx",
                collision_hint="simple convex collision, authored at UE centimeter scale",
            )
        )
    enriched_jobs = enrich_blender_plan(
        BlenderAssetPlan(
            job_name=f"{spec.title} Greybox Asset Pass",
            jobs=jobs,
            python_entrypoint="apps/blender-worker/app/procedural_asset_job.py",
            handoff_artifacts=[],
        )
    ).jobs
    seen_kinds.update(job.asset_kind for job in enriched_jobs)

    for asset_name, purpose, asset_kind in BLENDER_KIT_JOBS:
        if asset_kind in seen_kinds:
            continue
        jobs.append(
            BlenderAssetJob(
                asset_name=asset_name,
                purpose=purpose,
                primitive_strategy="gameplay-readable primitive composition generated by bpy",
                export_path=f"generated/assets/{asset_name}.fbx",
                collision_hint="UCX convex collision generated with matching bounds",
                asset_kind=asset_kind,
            )
        )
        seen_kinds.add(asset_kind)

    return enrich_blender_plan(
        BlenderAssetPlan(
            job_name=f"{spec.title} Greybox Asset Pass",
            jobs=jobs,
            python_entrypoint="apps/blender-worker/app/procedural_asset_job.py",
            handoff_artifacts=[
                "generated/assets/*.fbx",
                "generated/blender/*.py",
                "generated/blender-asset-plan.yaml",
                "generated/import-manifest.yaml",
            ],
        )
    )


def prepare_comfyui_visuals(spec: GameplaySpec) -> ComfyUIVisualPlan:
    title_slug = spec.title.lower().replace(" ", "_")
    visual_basis = ", ".join(spec.design_pillars[:2])
    return ComfyUIVisualPlan(
        plan_name=f"{spec.title} Visual Reference Pass",
        jobs=[
            ComfyUIPromptJob(
                job_id="concept_readability_reference",
                purpose="concept_reference",
                prompt=(
                    f"Gameplay readability concept art for {spec.title}: {spec.logline} "
                    f"Focus on clear player objective, hazard readability, simple shapes, {visual_basis}."
                ),
                negative_prompt=(
                    "busy composition, photorealistic noise, unreadable silhouettes, cinematic blur, "
                    "AAA marketing render, disconnected decorative detail"
                ),
                workflow_template="templates/comfyui/readability-reference.json",
                output_path=f"generated/comfyui/{title_slug}/concept_readability_reference.png",
                gameplay_constraint="Must clarify objective, hazard, route, or player feedback.",
            ),
            ComfyUIPromptJob(
                job_id="material_palette_reference",
                purpose="material_reference",
                prompt=(
                    f"Compact material and color reference board for a playable greybox of {spec.title}. "
                    "Separate safe paths, hazards, interactables, objectives, and exit affordances."
                ),
                negative_prompt=(
                    "single-color palette, low contrast, decorative-only swatches, noisy texture sheet"
                ),
                workflow_template="templates/comfyui/material-palette.json",
                output_path=f"generated/comfyui/{title_slug}/material_palette_reference.png",
                gameplay_constraint="Every color group must map to a gameplay state or affordance.",
            ),
            ComfyUIPromptJob(
                job_id="objective_ui_reference",
                purpose="ui_reference",
                prompt=(
                    f"Minimal objective tracker reference for {spec.title}, game jam prototype UI, "
                    "clear current objective, pressure indicator, restart readable in a 10-foot UI test."
                ),
                negative_prompt="ornate UI, tiny text, decorative panels, unreadable labels, dense HUD",
                workflow_template="templates/comfyui/ui-reference.json",
                output_path=f"generated/comfyui/{title_slug}/objective_ui_reference.png",
                gameplay_constraint="UI reference must support objective clarity before visual style.",
            ),
        ],
        workflow_templates=[
            "templates/comfyui/readability-reference.json",
            "templates/comfyui/material-palette.json",
            "templates/comfyui/ui-reference.json",
        ],
        handoff_artifacts=[
            "generated/comfyui/*/*.png",
            "generated/comfyui/comfyui-visual-plan.yaml",
            "generated/comfyui/run-manifest.yaml",
        ],
        usage_rules=[
            "ComfyUI outputs are references, not proof of playable progress.",
            "Do not block UE greybox implementation on image generation.",
            "Every generated visual must map to objective clarity, hazard readability, or UI feedback.",
            "Generated images require review before becoming Unreal textures or UI assets.",
        ],
    )


def prepare_qa_plan(spec: GameplaySpec) -> QAPlan:
    return QAPlan(
        target_session_minutes=spec.target_session_minutes,
        smoke_tests=[
            "Project opens without missing plugin or asset errors",
            "Prototype map loads directly from editor and packaged build",
            "Player can restart a run without reloading the map manually",
        ],
        playability_checks=[
            "Primary objective is visible within 10 seconds",
            "Each core verb is required at least once before the final beat",
            "A first-time player can identify why they failed",
            "The full loop completes in the target session window",
        ],
        failure_checks=spec.failure_states,
        packaging_checks=[
            "Windows development package builds",
            "Default map is the prototype map",
            "Input mappings are included in packaged build",
            "Generated assets have valid collision",
        ],
        metrics=[
            "time_to_first_objective",
            "attempts_to_first_completion",
            "failure_reason_distribution",
            "average_session_minutes",
        ],
    )


def decompose_production_tasks(request: PromptRequest) -> DirectorTaskBreakdown:
    gameplay_spec = design_from_prompt(request)
    return _build_task_breakdown(
        request=request,
        spec=gameplay_spec,
        unreal_plan=prepare_unreal_project(gameplay_spec, request.engine_version),
        blender_plan=prepare_blender_assets(gameplay_spec),
        comfyui_plan=prepare_comfyui_visuals(gameplay_spec),
        qa_plan=prepare_qa_plan(gameplay_spec),
    )


def _task(
    *,
    task_id: str,
    title: str,
    title_zh: str,
    agent: str,
    purpose: str,
    inputs: list[str],
    outputs: list[str],
    side_effects: list[str] | None = None,
    depends_on: list[str] | None = None,
    artifacts: list[str] | None = None,
    status: str = "pending",
    requires_confirmation: bool = False,
    risks: list[str] | None = None,
) -> ProductionTask:
    return ProductionTask(
        id=task_id,
        title=title,
        title_i18n={"en": title, "zh-CN": title_zh},
        agent=agent,  # type: ignore[arg-type]
        purpose=purpose,
        inputs=inputs,
        outputs=outputs,
        side_effects=side_effects or [],
        depends_on=depends_on or [],
        artifacts=artifacts or [],
        status=status,  # type: ignore[arg-type]
        requires_confirmation=requires_confirmation,
        risks=risks or [],
    )


def _build_task_breakdown(
    *,
    request: PromptRequest,
    spec: GameplaySpec,
    unreal_plan: UnrealProjectPlan,
    blender_plan: BlenderAssetPlan,
    comfyui_plan: ComfyUIVisualPlan,
    qa_plan: QAPlan,
) -> DirectorTaskBreakdown:
    tasks = [
        _task(
            task_id="gameplay_spec_review",
            title="Gameplay spec review",
            title_zh="玩法规格审查",
            agent="gameplay-agent",
            purpose="Validate the core loop, verbs, pacing, progression, win state, and failure states.",
            inputs=["PromptRequest", "user constraints"],
            outputs=["GameplaySpec"],
            artifacts=["generated/gameplay-spec.yaml"],
            status="ready",
            risks=["Reject mechanics that do not change player decisions."],
        ),
        _task(
            task_id="gdd_generation",
            title="Structured GDD generation",
            title_zh="结构化 GDD 生成",
            agent="gdd-writer",
            purpose="Render implementation-facing markdown without adding unapproved features.",
            inputs=["GameplaySpec"],
            outputs=["GDDDocument"],
            depends_on=["gameplay_spec_review"],
            artifacts=["generated/gdd.md"],
            status="ready",
        ),
        _task(
            task_id="level_beat_plan",
            title="Level beat plan",
            title_zh="关卡节奏计划",
            agent="level-director",
            purpose="Turn the loop into first-minute teaching, midpoint combination, and final challenge beats.",
            inputs=["GameplaySpec.level_beats", "GameplaySpec.asset_needs"],
            outputs=["level beat plan", "greybox requirements"],
            depends_on=["gameplay_spec_review"],
            artifacts=["generated/level-beats.yaml"],
            status="ready",
        ),
        _task(
            task_id="blender_asset_plan",
            title="Blender asset plan",
            title_zh="Blender 资产计划",
            agent="blender-worker",
            purpose=f"Prepare {len(blender_plan.jobs)} modular greybox asset jobs for readable play.",
            inputs=["GameplaySpec.asset_needs"],
            outputs=["BlenderAssetPlan", "Unreal import manifest plan"],
            depends_on=["level_beat_plan"],
            artifacts=["generated/blender-asset-plan.yaml"],
            status="ready",
        ),
        _task(
            task_id="blender_asset_generation",
            title="Generate Blender assets",
            title_zh="生成 Blender 资产",
            agent="blender-worker",
            purpose="Run approved Blender Python to create scale-correct FBX or GLB greybox assets.",
            inputs=["BlenderAssetPlan"],
            outputs=["FBX or GLB exports", "UnrealImportManifest"],
            side_effects=[
                "launches Blender",
                "writes generated/blender scripts",
                "writes generated/assets mesh exports",
            ],
            depends_on=["blender_asset_plan"],
            artifacts=["generated/assets/*.fbx", "generated/import-manifest.yaml"],
            status="pending",
            requires_confirmation=True,
        ),
        _task(
            task_id="comfyui_visual_plan",
            title="ComfyUI visual plan",
            title_zh="ComfyUI 视觉计划",
            agent="comfyui-worker",
            purpose=f"Prepare {len(comfyui_plan.jobs)} gameplay-readable reference jobs.",
            inputs=["GameplaySpec.notes_for_comfyui", "GameplaySpec.design_pillars"],
            outputs=["ComfyUIVisualPlan"],
            depends_on=["gameplay_spec_review"],
            artifacts=["generated/comfyui/comfyui-visual-plan.yaml"],
            status="ready",
        ),
        _task(
            task_id="comfyui_reference_generation",
            title="Generate ComfyUI references",
            title_zh="生成 ComfyUI 参考图",
            agent="comfyui-worker",
            purpose="Submit approved local ComfyUI workflow jobs for readability, material, and UI references.",
            inputs=["ComfyUIVisualPlan", "local ComfyUI checkpoint"],
            outputs=["review reference images", "ComfyUIRunManifest"],
            side_effects=[
                "submits ComfyUI prompt jobs",
                "writes generated/comfyui images",
                "writes generated/logs/comfyui logs",
            ],
            depends_on=["comfyui_visual_plan"],
            artifacts=["generated/comfyui/*/*.png", "generated/comfyui/run-manifest.json"],
            status="pending",
            requires_confirmation=True,
            risks=["References must be reviewed before becoming UE textures or UI assets."],
        ),
        _task(
            task_id="unreal_project_setup",
            title="Unreal project setup",
            title_zh="Unreal 项目搭建",
            agent="unreal-builder",
            purpose=f"Prepare {unreal_plan.project_name} folders, plugins, maps, classes, and setup scripts.",
            inputs=["UnrealProjectPlan", "GameplaySpec"],
            outputs=["UE project structure", "content manifest", "setup script"],
            side_effects=[
                "writes generated/unreal project files",
                "creates generated Unreal content folders",
            ],
            depends_on=["gameplay_spec_review", "level_beat_plan"],
            artifacts=["generated/unreal/**/*.uproject", "generated/unreal/content-manifest.json"],
            status="pending",
            requires_confirmation=True,
            risks=["Requires a compatible local Unreal Engine installation before editor validation."],
        ),
        _task(
            task_id="unreal_asset_ingest",
            title="Unreal asset ingest",
            title_zh="Unreal 资产导入",
            agent="unreal-builder",
            purpose="Move reviewed Blender and ComfyUI outputs into the generated Unreal project.",
            inputs=["UnrealAssetIngestManifest", "Blender exports", "reviewed ComfyUI references"],
            outputs=["imported UE assets", "ingest logs"],
            side_effects=["launches Unreal Editor", "imports generated assets into Content"],
            depends_on=[
                "unreal_project_setup",
                "blender_asset_generation",
                "comfyui_reference_generation",
            ],
            artifacts=["generated/unreal/*/Content/**", "generated/logs/unreal/*.log"],
            status="blocked",
            requires_confirmation=True,
            risks=["Blocked until source assets exist and the UE project has been generated."],
        ),
        _task(
            task_id="qa_plan",
            title="QA plan",
            title_zh="QA 计划",
            agent="qa-agent",
            purpose=f"Prepare smoke, playability, failure, and packaging checks for {qa_plan.target_session_minutes} minutes.",
            inputs=["GameplaySpec", "UnrealProjectPlan"],
            outputs=["QAPlan"],
            depends_on=["gameplay_spec_review"],
            artifacts=["generated/qa-plan.yaml"],
            status="ready",
        ),
        _task(
            task_id="playability_smoke_test",
            title="Playability smoke test",
            title_zh="可玩性冒烟测试",
            agent="qa-agent",
            purpose="Verify objective readability, restart flow, collision, map load, and package readiness.",
            inputs=["generated Unreal project", "imported assets", "QAPlan"],
            outputs=["QA report", "blocking issues"],
            side_effects=["runs Unreal commandlets or packaged build checks"],
            depends_on=["unreal_asset_ingest", "qa_plan"],
            artifacts=["generated/qa-report.json", "generated/logs/qa/*.log"],
            status="blocked",
            requires_confirmation=True,
            risks=["Run this before visual polish or packaging expansion."],
        ),
    ]
    goal = f"Produce a {spec.target_session_minutes}-minute playable vertical slice for {spec.title}."
    return DirectorTaskBreakdown(
        source_prompt=request.prompt,
        goal=goal,
        goal_i18n={
            "en": goal,
            "zh-CN": f"为 {spec.title} 制作一个 {spec.target_session_minutes} 分钟的可玩垂直切片。",
        },
        tasks=tasks,
        recommended_next_task="gameplay_spec_review",
        risks=[
            "Execution tasks require explicit confirmation before local tool side effects.",
            "Prefer greybox playability before visual expansion.",
            "Unreal, Blender, and ComfyUI availability should be probed before execution.",
        ],
        next_actions=DIRECTOR_NEXT_ACTIONS,
        confirmation_required=any(task.requires_confirmation for task in tasks),
        i18n=spec.i18n,
    )


def run_director_workflow(request: PromptRequest) -> DirectorBuildPlan:
    gameplay_spec = design_from_prompt(request)
    unreal_plan = prepare_unreal_project(gameplay_spec, request.engine_version)
    blender_plan = prepare_blender_assets(gameplay_spec)
    comfyui_plan = prepare_comfyui_visuals(gameplay_spec)
    qa_plan = prepare_qa_plan(gameplay_spec)
    return DirectorBuildPlan(
        gameplay_spec=gameplay_spec,
        gdd=render_gdd(gameplay_spec),
        unreal_plan=unreal_plan,
        blender_plan=blender_plan,
        comfyui_plan=comfyui_plan,
        qa_plan=qa_plan,
        task_breakdown=_build_task_breakdown(
            request=request,
            spec=gameplay_spec,
            unreal_plan=unreal_plan,
            blender_plan=blender_plan,
            comfyui_plan=comfyui_plan,
            qa_plan=qa_plan,
        ),
        next_actions=DIRECTOR_NEXT_ACTIONS,
    )
